
وده طبيعي جدًا لأنك بتستخدم Firebase + Kinde SDK → اللي محتاج **Node.js runtime**، بينما **Edge Functions بتشتغل في بيئة V8 runtime (مش Node.js)** وبالتالي مش بتسمح باستخدام `fs`, `crypto`, `firebase-admin` ... الخ.  

---

## ✅ الحل النهائي
اللي محتاج تعمله هو **تعطيل Edge Functions نهائيًا** عشان Netlify ما يحاولش يولدها.  

1. في جذر المشروع، افتح أو أنشئ ملف `netlify.toml`.  
2. حط الإعدادات دي:

```toml
[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase", "firebase-admin", "@kinde-oss/kinde-nodejs-sdk"]

[build.environment]
  NODE_VERSION = "18"

# ✨ ده أهم جزء → بيوقف الـ Edge Functions
[experimental]
  edge_functions = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
